services:
  api:
    build: ./backend
    ports:
      - "${API_PORT:-8001}:8000"
    depends_on:
      - postgres
      - redis
    profiles: ["dev"]

  front:
    build: ./frontend
    ports:
      - "${FRONT_PORT:-5173}:5173"
    profiles: ["dev"]

  caddy:
    image: caddy:2
    ports:
      - "${CADDY_HTTP_PORT:-8080}:80"
    profiles: ["dev"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    profiles: ["dev"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    profiles: ["dev"]

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    profiles: ["obs"]

  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - "9090:9090"
    profiles: ["obs"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - "8081:8080"
    profiles: ["obs"]

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    profiles: ["obs"]

  promtail:
    image: grafana/promtail:2.9.4
    profiles: ["obs"]
